#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JobScheduler.Resource", IsApplication=true)]

namespace JobScheduler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int none_received = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int start_received = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int stop_received = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int horizontal_page_margin = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int margin_huge = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int margin_large = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int margin_medium = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int margin_small = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int margin_tiny = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int vertical_page_margin = 2131165190;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tile = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int cancel_button = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int checkbox_any = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int checkbox_charging = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int checkbox_idle = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int checkbox_unmetered = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int deadline_time = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int delay_time = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int finished_button = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int onstart_textview = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int onstop_textview = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int schedule_button = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int task_params = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sample_main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000e
			public const int any = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int cancel_all_jobs_button_text = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int charging_caption = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int charging_text = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int connectivity = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int constraints = 2130968588;
			
			// aapt resource value: 0x7f040012
			public const int deadline = 2130968594;
			
			// aapt resource value: 0x7f040004
			public const int defaultparamtext = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int delay = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int finish_job_button_text = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int idle_caption = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int idle_mode_text = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int intro_message = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int onstarttask = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int onstoptask = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int schedule_job_button_text = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int timing = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int unmetered = 2130968591;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int AppTheme = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Base = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Sample = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Widget = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget_SampleMessage = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Widget_SampleMessageTile = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
